<template>
  <q-list
    separator
    no-padding
  >
    <q-item
      v-for="item in 20"
      :key="item"
    >
      <q-item-section avatar>
        <q-skeleton
          size="100px"
          square
          animation="fade"
        />
      </q-item-section>

      <q-item-section>
        <q-skeleton
          type="text"
          square
          height="16px"
          width="20vw"
          animation="fade"
        />
        <q-skeleton
          type="text"
          square
          height="16px"
          width="30vw"
          animation="fade"
        />
        <q-skeleton
          type="text"
          square
          height="16px"
          width="40vw"
          animation="fade"
        />
        <q-skeleton
          type="text"
          square
          height="16px"
          width="40vw"
          animation="fade"
        />
        <q-skeleton
          type="text"
          square
          height="16px"
          width="10vw"
          animation="fade"
        />
        <q-skeleton
          type="text"
          square
          height="16px"
          width="12vw"
          animation="fade"
        />
      </q-item-section>

      <q-item-section
        side
        top
      >
        <q-skeleton
          animation="blink"
          type="text"
          width="80px"
          height="50px"
        />
        <q-skeleton
          animation="blink"
          type="text"
          width="80px"
          height="50px"
        />
      </q-item-section>
    </q-item>
  </q-list>
</template>
